defaults: &workdir
  working_directory: ~/auth0-logs-to-datadog

defaults: &node
  <<: *workdir
  docker:
    - image: circleci/node:6

defaults: &aws
  <<: *workdir
  docker:
    - image: projectwave/nodejs-awscli
      environment:
        AWS_DEFAULT_REGION: eu-west-2

version: 2
jobs:
  build:
    <<: *node
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Check code formatting
          command: yarn lint:js
      - run:
          name: Build client and server bundles
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist/*.js
            - dist/*.css
            - dist/*.map
            - dist/*.json

  assets:
    <<: *aws
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Set AWS variables in the environment
          command: |
            echo 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_DEV' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY_DEV' >> $BASH_ENV
      - run:
          name: Deploying assets to S3
          command: aws s3 sync --delete ./dist s3://config.dev.astoapp.co.uk/assets/auth0

  tag:
    <<: *node
    steps:
      - checkout
      - run:
          name: Create and push git tag
          command: yarn run tag

workflows:
  version: 2
  release:
    jobs:
      - build
      - assets:
          context: default
          requires:
            - build
          filters:
            branches:
              only: master
      - tag:
          context: default
          requires:
            - assets
          filters:
            branches:
              only: master
